---
- name: print global variables
  debug: 
    msg: "run step2 {{ global_default }}"

- name: print local variables in step1
  debug: 
    msg: "run step2 {{ local_var }} {{ local_default }}"

- name: print global variables in group_vars
  debug:
    msg: "run step2 {{ global_variable }}"
