---
- name: install filebeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.13.1-x86_64.rpm
    state: latest
  when: ansible_distribution == "CentOS"

- name: install filebeat
  apt:
    deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.13.1-amd64.deb
  when: ansible_distribution == "Ubuntu"

- name: generate filebeat.yml with backup
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    backup: yes
